---
title: "Data Exploration"
author: "Andy Shen"
date: "10/27/2020"
output: pdf_document
---

# Traditional Techniques

```{r,message=FALSE}
rm(list = ls())
library(MASS) #lda, qda
library(class) #knn
library(tidyverse)
library(caret)
```

```{r}
find_score <- function(conf_mat) {
  print(sum(diag(conf_mat) * c(1, 20, 20)))
  final <- sum(diag(conf_mat) * c(1, 20, 20)) / sum(apply(conf_mat, 2, sum) * c(1, 20, 20))
  final
}
```


```{r}
setwd("/Users/andyshen/Desktop/Git/Stats-101C-F20/Midterm Project")
train <- read.csv("training.csv", stringsAsFactors = TRUE)
test <- read.csv("test.csv", stringsAsFactors = TRUE)
train$class <- factor(train$class)
levels(train$class) <- c("NG", "OG", "TSG")
test$class <- factor(test$class)
levels(test$class) <- c("NG", "OG", "TSG")
```

```{r}
set.seed(110920)
samp <- sample(1:nrow(train), floor(0.8 * nrow(train)), replace = FALSE)
train1 <- train[samp, ]
test_train <- train[-samp, ]
```


FamilyMemberCount, RVIS_percentile, N_Missense, intolerant_pNull, Gene_age, pLOF_Zscore

VEST_score

## LDA

```{r}
lda.mod <- lda(
  class ~ FamilyMemberCount + RVIS_percentile + N_Missense + 
    intolerant_pNull + Gene_age + pLOF_Zscore, data = train1
)
preds <- predict(lda.mod, test_train, type = "response")$posterior
preds <- apply(preds, 1, which.max) - 1
tbl <- table(preds, test_train$class)
ter <- sum(diag(tbl)) / sum(tbl)
tbl
```

Test error rate is `r round(1-ter, 3)`. 

\pagebreak

## QDA

```{r}
qda.mod <- qda(
  class ~ FamilyMemberCount + RVIS_percentile + N_Missense + 
    intolerant_pNull + Gene_age + pLOF_Zscore, data = train1
)
preds <- predict(qda.mod, test_train, type = "response")$posterior
preds <- apply(preds, 1, which.max) - 1
tbl <- table(preds, test_train$class)
ter <- sum(diag(tbl)) / sum(tbl)
tbl
```

Test error rate is `r round(1-ter, 3)`

\pagebreak

## KNN

```{r}
train1k <- train1 %>% dplyr::select(-class)
test_traink <- test_train %>% dplyr::select(-class)

for(col in 1:ncol(train1k)) {
  train1k[, col] <- train1k[, col] / max(train1k[, col])
  test_traink[, col] <- test_traink[, col] / max(test_traink[, col])
} #standardizing. ncol(test) == ncol(train)

trainx <- train1k %>% dplyr::select(
  FamilyMemberCount, RVIS_percentile, N_Missense, intolerant_pNull, Gene_age, pLOF_Zscore
)
trainy <- train1$class

testx <- test_traink %>% dplyr::select(
  FamilyMemberCount, RVIS_percentile, N_Missense, intolerant_pNull, Gene_age, pLOF_Zscore
)
testy <- test_train$class

rows <- 40
knn_mat <- matrix(NA, nrow = rows, ncol = length(testy))
error_rate <- rep(NA, rows)
for(i in 1:rows) {
  knn_mat[i,] <- knn(trainx, testx, trainy, k = i)
  tbl <- table("actual" = testy, "predicted" =  knn_mat[i,])
  error_rate[i] <- 1 - (sum(diag(tbl)) / sum(tbl))
}
plot(error_rate, type = "l", col = "dodgerblue")
points(error_rate, pch = 19, col = "dodgerblue")
best <- which.min(error_rate)
best_tbl <- table("actual" = testy, "predicted" =  knn_mat[best,])
best_tbl
ter <- sum(diag(best_tbl)) / sum(best_tbl)
```


Test error rate is `r round(1-ter, 3)`. This is for K = `r best`. 

\pagebreak

# Using `caret`

```{r}
tc <- trainControl(
  method = "cv", number = 5, classProbs = TRUE, savePredictions = TRUE
) # setting up training technique
```


## LDA

```{r}
LDAfit <- caret::train(
  class ~ FamilyMemberCount + RVIS_percentile + N_Missense + 
    intolerant_pNull + Gene_age + pLOF_Zscore, 
  data = train1, method = "lda",
  preProc = c("center", "scale"),
  trControl = tc
)
preds <- predict(LDAfit, test_train)
tbl <- table(preds, test_train$class)
acc <- find_score(tbl)
tbl
acc
```


## QDA

```{r}
QDAfit <- caret::train(
  class ~ FamilyMemberCount + RVIS_percentile + N_Missense + 
    intolerant_pNull + Gene_age + pLOF_Zscore, 
  data = train1, method = "qda",
  preProc = c("center", "scale"),
  trControl = tc
)
preds <- predict(QDAfit, test_train)
tbl <- table(preds, test_train$class)
acc <- find_score(tbl)
tbl
acc
```

## Logistic Regression

```{r, error=TRUE}
LRfit <- caret::train(
  class ~ FamilyMemberCount + RVIS_percentile + N_Missense + 
    intolerant_pNull + Gene_age + pLOF_Zscore, 
  data = train1, method = "glm", family = "binomial",
  preProc = c("center", "scale"),
  trControl = tc
)
```


## KNN

```{r}
KNNfit <- caret::train(
  class ~ FamilyMemberCount + RVIS_percentile + N_Missense + 
    intolerant_pNull + Gene_age + pLOF_Zscore, data = train1,
  method = "knn", preProc = c("center", "scale"), trControl = tc
)
ggplot(KNNfit) + theme_bw()
preds <- predict(LDAfit, test_train)
tbl <- table(preds, test_train$class)
acc <- find_score(tbl)
tbl
acc
```





